version: '3.8'

services:
  postgres:
    restart: always
    container_name: playlist
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playlist
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data/pgdata